# Generated by Django 5.2.17 on 2026-10-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(help_text='Class name, e.g. Class 10', max_length=64),
        ),
    ]
