# Generated by Django 5.2.17 on 2026-10-09 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_classroom_class_teacher'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Empty means whole-day class-teacher attendance.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='academics.subject'),
        ),
    ]
